HelloWorld: Use ConsolePrint to simplify code and fix GCC build
AsciiSprint takes a CHAR8 buffer to write to whereas ConsoleWrite
expects a UINT8 buffer. This causes GCC to complain:

/.../sources/slimbootloader/PayloadPkg/HelloWorld/HelloWorld.c: In function ‘PayloadMain’:
/.../sources/slimbootloader/PayloadPkg/HelloWorld/HelloWorld.c:36:25: error: pointer targets in passing argument 1 of ‘ConsoleWrite’ differ in signedness [-Werror=pointer-sign]
   36 |           ConsoleWrite (Message, Len);
      |                         ^~~~~~~
      |                         |
      |                         CHAR8 * {aka char *}
In file included from /.../sources/slimbootloader/PayloadPkg/HelloWorld/HelloWorld.h:18,
                 from /.../sources/slimbootloader/PayloadPkg/HelloWorld/HelloWorld.c:8:
/.../sources/slimbootloader/BootloaderCommonPkg/Include/Library/ConsoleOutLib.h:103:17: note: expected ‘UINT8 *’ {aka ‘unsigned char *’} but argument is of type ‘CHAR8 *’ {aka ‘char *’}
  103 |   IN UINT8     *Buffer,
      |      ~~~~~~~~~~~^~~~~~

Let's avoid the whole problem and simplify the code too by just calling
ConsolePrint instead.

Signed-off-by: Mike Crowe <mac@mcrowe.com>