fix: [toolchain] zero extension warning from 'UINTN' to 'UINT64'
This commit addresses the build error encountered in the Azure CI build pipeline.
The build process was halted due to a fatal error (NMAKE : fatal error U1077).

  (skip)
  d:\a\1\s\BootloaderCommonPkg\Library\FullMemoryAllocationLib\Page.c(748): error C2220: the following warning is treated as an error
  d:\a\1\s\BootloaderCommonPkg\Library\FullMemoryAllocationLib\Page.c(748): warning C4319: '~': zero extending 'UINTN' to 'UINT64' of greater size
  PayloadLib.c
  NMAKE : fatal error U1077: (skip)

Signed-off-by: Stanley Chang <stanley.chang@intel.com>